import argon2 from 'argon2';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { buildApp, type ProductionCore } from '../../apps/api/src/app.js';

const orgA='11111111-1111-4111-8111-111111111111'; const year='11111111-1111-4111-8111-111111111115'; const snapshot='11111111-1111-4111-8111-111111111137';
const env={...process.env,NODE_ENV:'development',DATABASE_URL:process.env.DATABASE_URL ?? 'postgresql://dentpilot_app:development-only-change-me@localhost:5432/dentpilot',MINIO_ENDPOINT:process.env.MINIO_ENDPOINT ?? 'http://localhost:9000',MINIO_ACCESS_KEY:process.env.MINIO_ACCESS_KEY ?? 'minioadmin',MINIO_SECRET_KEY:process.env.MINIO_SECRET_KEY ?? 'minio-development-only-change-me',SESSION_COOKIE_SECRET:'this-is-a-test-only-session-cookie-secret-value',CORS_ORIGIN:'http://localhost:5173'};
let core: ProductionCore; let loginSequence=10;
function cookies(setCookie: string | string[] | undefined): { header:string; csrf:string } { const items=Array.isArray(setCookie)?setCookie:[setCookie ?? '']; const session=items.find((item)=>item.startsWith('dp_session='))?.split(';')[0] ?? ''; const csrf=items.find((item)=>item.startsWith('dp_csrf='))?.split(';')[0] ?? ''; return {header:`${session}; ${csrf}`,csrf:decodeURIComponent(csrf.split('=').slice(1).join('='))}; }
async function login(email:string,password='development-only-password'): Promise<{header:string;csrf:string}> { const response=await core.app.inject({method:'POST',url:'/api/v1/auth/login',remoteAddress:`127.0.0.${loginSequence++}`,payload:{organizationId:orgA,email,password}}); expect(response.statusCode).toBe(204); return cookies(response.headers['set-cookie']); }

describe('HTTP authentication and authorization',()=>{
  beforeAll(async()=>{core=await buildApp(env);}); afterAll(async()=>core.app.close());
  it('answers live and readiness health against real dependencies',async()=>{expect((await core.app.inject('/health/live')).statusCode).toBe(200);expect((await core.app.inject('/health/ready')).statusCode).toBe(200);});
  it('denies disabled account login and does not leak session',async()=>{const response=await core.app.inject({method:'POST',url:'/api/v1/auth/login',remoteAddress:`127.0.0.${loginSequence++}`,payload:{organizationId:orgA,email:'disabled@dev.dentpilot.local',password:'development-only-password'}});expect(response.statusCode).toBe(403);expect(response.json().error.code).toBe('ACCOUNT_DISABLED');});
  it('requires a valid CSRF token for a protected mutation',async()=>{const auth=await login('admin@dev.dentpilot.local');const response=await core.app.inject({method:'POST',url:'/api/v1/invitations',headers:{cookie:auth.header},payload:{email:'new@dev.dentpilot.local',role:'DEPARTMENT_ADMIN'}});expect(response.statusCode).toBe(403);expect(response.json().error.code).toBe('CSRF_INVALID');});
  it('rejects client role manipulation and returns aggregate-only report DTOs',async()=>{const auth=await login('supervisor@dev.dentpilot.local');const students=await core.app.inject({method:'GET',url:'/api/v1/students?role=UNIVERSITY_ADMIN',headers:{cookie:auth.header}});expect(students.statusCode).toBe(200);const report=await core.app.inject({method:'GET',url:`/api/v1/reports/aggregate?academicYearId=${year}`,headers:{cookie:auth.header}});expect(report.statusCode).toBe(403);const admin=await login('admin@dev.dentpilot.local');const allowed=await core.app.inject({method:'GET',url:`/api/v1/reports/aggregate?academicYearId=${year}`,headers:{cookie:admin.header}});expect(allowed.statusCode).toBe(200);const body=allowed.json();expect(body).not.toHaveProperty('studentId');expect(body).not.toHaveProperty('displayName');});
  it('requires active supervisor assignment permission for staff submission access',async()=>{const dept=await login('dept.admin@dev.dentpilot.local');const response=await core.app.inject({method:'GET',url:`/api/v1/staff/submissions/${snapshot}`,headers:{cookie:dept.header}});expect(response.statusCode).toBe(403);});
  it('revokes the session at logout',async()=>{const auth=await login('admin@dev.dentpilot.local');const logout=await core.app.inject({method:'POST',url:'/api/v1/auth/logout',headers:{cookie:auth.header,'x-csrf-token':auth.csrf}});expect(logout.statusCode).toBe(204);const session=await core.app.inject({method:'GET',url:'/api/v1/session',headers:{cookie:auth.header}});expect(session.statusCode).toBe(401);});
  it('enforces invitation single-use and expiry-compatible path',async()=>{const auth=await login('admin@dev.dentpilot.local');const created=await core.app.inject({method:'POST',url:'/api/v1/invitations',headers:{cookie:auth.header,'x-csrf-token':auth.csrf},payload:{email:`invite-${Date.now()}@dev.dentpilot.local`,role:'DEPARTMENT_ADMIN'}});expect(created.statusCode).toBe(201);const token=created.json().invitationToken;const redeemPayload={organizationId:orgA,token,password:'new-development-password'};expect((await core.app.inject({method:'POST',url:'/api/v1/invitations/redeem',payload:redeemPayload})).statusCode).toBe(204);expect((await core.app.inject({method:'POST',url:'/api/v1/invitations/redeem',payload:redeemPayload})).statusCode).toBe(400);});
  it('prevents cross-tenant data access through guessed submission IDs',async()=>{const hash=await argon2.hash('tenant-b-development-password',{type:argon2.argon2id});const orgB='22222222-2222-4222-8222-222222222222';const adminB='22222222-2222-4222-8222-222222222223';await core.db.pool.query('INSERT INTO organizations(id,name,slug) VALUES($1,$2,$3) ON CONFLICT DO NOTHING',[orgB,'Tenant B','tenant-b']);await core.db.withTenant({organizationId:orgB},async(client)=>{await client.query('INSERT INTO colleges(organization_id,name) VALUES($1,$2) ON CONFLICT DO NOTHING',[orgB,'College B']);await client.query('INSERT INTO accounts(id,organization_id,email,password_hash,status,primary_role) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT DO NOTHING',[adminB,orgB,'admin@tenant-b.local',hash,'ACTIVE','UNIVERSITY_ADMIN']);});const response=await core.app.inject({method:'POST',url:'/api/v1/auth/login',remoteAddress:`127.0.0.${loginSequence++}`,payload:{organizationId:orgB,email:'admin@tenant-b.local',password:'tenant-b-development-password'}});const auth=cookies(response.headers['set-cookie']);const denied=await core.app.inject({method:'GET',url:`/api/v1/staff/submissions/${snapshot}`,headers:{cookie:auth.header}});expect(denied.statusCode).toBe(404);});
});
