CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS citext;

CREATE TYPE account_status AS ENUM ('PENDING','ACTIVE','DISABLED');
CREATE TYPE role_code AS ENUM ('UNIVERSITY_ADMIN','DEPARTMENT_ADMIN','CLINICAL_SUPERVISOR','STUDENT_INTEGRATION');
CREATE TYPE enrollment_status AS ENUM ('ACTIVE','CLOSED');
CREATE TYPE lifecycle_status AS ENUM ('ACTIVE','CLOSED','REMOVED','ARCHIVED');
CREATE TYPE distribution_mode AS ENUM ('FULL_COHORT','GROUPS_ENABLED');
CREATE TYPE version_status AS ENUM ('DRAFT','PUBLISHED','ARCHIVED');
CREATE TYPE submission_status AS ENUM ('DRAFT','SUBMITTED','REVISION_REQUESTED','APPROVED_START','APPROVED_FINAL','GRADED');
CREATE TYPE term_result_status AS ENUM ('DRAFT','REVIEWED','APPROVED','LOCKED','REOPENED');

CREATE TABLE organizations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, slug text NOT NULL UNIQUE, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE colleges (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), name text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (organization_id, name));
CREATE TABLE departments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), college_id uuid NOT NULL REFERENCES colleges(id), code text NOT NULL, name text NOT NULL, active boolean NOT NULL DEFAULT true, revision integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (organization_id, code));
CREATE TABLE academic_years (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), label text NOT NULL, starts_on date NOT NULL, ends_on date NOT NULL, status lifecycle_status NOT NULL DEFAULT 'ACTIVE', revision integer NOT NULL DEFAULT 1, CHECK (ends_on > starts_on), UNIQUE (organization_id, label));
CREATE TABLE terms (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), academic_year_id uuid NOT NULL REFERENCES academic_years(id), label text NOT NULL, starts_on date NOT NULL, ends_on date NOT NULL, status lifecycle_status NOT NULL DEFAULT 'ACTIVE', CHECK (ends_on > starts_on), UNIQUE (organization_id, academic_year_id, label));
CREATE TABLE academic_levels (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), code text NOT NULL, label text NOT NULL, ordinal smallint NOT NULL, active boolean NOT NULL DEFAULT true, UNIQUE (organization_id, code), UNIQUE (organization_id, ordinal));
CREATE TABLE cohorts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), label text NOT NULL, active boolean NOT NULL DEFAULT true, UNIQUE (organization_id, label));

CREATE TABLE accounts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), college_id uuid REFERENCES colleges(id), email citext NOT NULL, password_hash text NOT NULL, status account_status NOT NULL DEFAULT 'PENDING', primary_role role_code NOT NULL, revision integer NOT NULL DEFAULT 1, last_login_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (organization_id, email));
CREATE TABLE account_scopes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), account_id uuid NOT NULL REFERENCES accounts(id), department_id uuid REFERENCES departments(id), academic_year_id uuid REFERENCES academic_years(id), academic_level_id uuid REFERENCES academic_levels(id), cohort_id uuid REFERENCES cohorts(id), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE sessions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), account_id uuid NOT NULL REFERENCES accounts(id), token_hash text NOT NULL UNIQUE, csrf_hash text NOT NULL, expires_at timestamptz NOT NULL, rotated_from_session_id uuid REFERENCES sessions(id), revoked_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE invitations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), email citext NOT NULL, role role_code NOT NULL, token_hash text NOT NULL UNIQUE, expires_at timestamptz NOT NULL, used_at timestamptz, revoked_at timestamptz, created_by_account_id uuid REFERENCES accounts(id), created_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE students (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), college_id uuid NOT NULL REFERENCES colleges(id), student_number text NOT NULL, display_name text NOT NULL, status lifecycle_status NOT NULL DEFAULT 'ACTIVE', revision integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (organization_id, student_number));
ALTER TABLE accounts ADD COLUMN student_id uuid REFERENCES students(id);
CREATE TABLE academic_enrollments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), student_id uuid NOT NULL REFERENCES students(id), academic_year_id uuid NOT NULL REFERENCES academic_years(id), academic_level_id uuid NOT NULL REFERENCES academic_levels(id), cohort_id uuid NOT NULL REFERENCES cohorts(id), status enrollment_status NOT NULL DEFAULT 'ACTIVE', started_at timestamptz NOT NULL DEFAULT now(), closed_at timestamptz, close_reason text, revision integer NOT NULL DEFAULT 1, CHECK ((status = 'ACTIVE' AND closed_at IS NULL) OR status = 'CLOSED'), UNIQUE (organization_id, student_id, academic_year_id, academic_level_id, cohort_id, status));
CREATE UNIQUE INDEX academic_enrollments_one_active_context ON academic_enrollments(organization_id, student_id, academic_year_id, academic_level_id, cohort_id) WHERE status='ACTIVE';
CREATE TABLE rosters (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), department_id uuid NOT NULL REFERENCES departments(id), academic_year_id uuid NOT NULL REFERENCES academic_years(id), academic_level_id uuid NOT NULL REFERENCES academic_levels(id), cohort_id uuid NOT NULL REFERENCES cohorts(id), status lifecycle_status NOT NULL DEFAULT 'ACTIVE', revision integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (organization_id, department_id, academic_year_id, academic_level_id, cohort_id));
CREATE TABLE roster_memberships (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), roster_id uuid NOT NULL REFERENCES rosters(id), student_id uuid NOT NULL REFERENCES students(id), enrollment_id uuid NOT NULL REFERENCES academic_enrollments(id), status lifecycle_status NOT NULL DEFAULT 'ACTIVE', added_at timestamptz NOT NULL DEFAULT now(), closed_at timestamptz, reason text, UNIQUE (organization_id, roster_id, enrollment_id, status));
CREATE UNIQUE INDEX roster_memberships_one_active ON roster_memberships(organization_id, roster_id, enrollment_id) WHERE status='ACTIVE';
CREATE TABLE department_distribution_policies (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), department_id uuid NOT NULL REFERENCES departments(id), academic_year_id uuid NOT NULL REFERENCES academic_years(id), academic_level_id uuid NOT NULL REFERENCES academic_levels(id), mode distribution_mode NOT NULL, revision integer NOT NULL DEFAULT 1, effective_at timestamptz NOT NULL DEFAULT now(), UNIQUE (organization_id, department_id, academic_year_id, academic_level_id));
CREATE TABLE academic_groups (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), department_id uuid NOT NULL REFERENCES departments(id), academic_year_id uuid NOT NULL REFERENCES academic_years(id), academic_level_id uuid NOT NULL REFERENCES academic_levels(id), name text NOT NULL, range_start integer, range_end integer, status lifecycle_status NOT NULL DEFAULT 'ACTIVE', revision integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), CHECK ((range_start IS NULL AND range_end IS NULL) OR (range_start >= 1 AND range_end >= range_start)), UNIQUE (organization_id, department_id, academic_year_id, academic_level_id, name));
CREATE TABLE group_memberships (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), group_id uuid NOT NULL REFERENCES academic_groups(id), department_id uuid NOT NULL REFERENCES departments(id), student_id uuid NOT NULL REFERENCES students(id), enrollment_id uuid NOT NULL REFERENCES academic_enrollments(id), status lifecycle_status NOT NULL DEFAULT 'ACTIVE', assigned_at timestamptz NOT NULL DEFAULT now(), removed_at timestamptz, reason text);
CREATE UNIQUE INDEX group_memberships_one_active_context ON group_memberships(organization_id, enrollment_id, department_id) WHERE status='ACTIVE';

CREATE TABLE faculty_profiles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), account_id uuid NOT NULL UNIQUE REFERENCES accounts(id), employee_number text NOT NULL, display_name text NOT NULL, active boolean NOT NULL DEFAULT true, UNIQUE (organization_id, employee_number));
CREATE TABLE supervisor_assignments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), supervisor_account_id uuid NOT NULL REFERENCES accounts(id), department_id uuid NOT NULL REFERENCES departments(id), academic_year_id uuid NOT NULL REFERENCES academic_years(id), academic_level_id uuid NOT NULL REFERENCES academic_levels(id), cohort_id uuid REFERENCES cohorts(id), group_id uuid REFERENCES academic_groups(id), status lifecycle_status NOT NULL DEFAULT 'ACTIVE', effective_from timestamptz NOT NULL DEFAULT now(), effective_to timestamptz, revision integer NOT NULL DEFAULT 1, reason text NOT NULL, created_by_account_id uuid REFERENCES accounts(id), CHECK (effective_to IS NULL OR effective_to > effective_from));
CREATE UNIQUE INDEX supervisor_assignments_one_active_scope ON supervisor_assignments(organization_id, supervisor_account_id, department_id, academic_year_id, academic_level_id, COALESCE(cohort_id, '00000000-0000-0000-0000-000000000000'), COALESCE(group_id, '00000000-0000-0000-0000-000000000000')) WHERE status='ACTIVE';
CREATE TABLE supervisor_assignment_permissions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), assignment_id uuid NOT NULL REFERENCES supervisor_assignments(id) ON DELETE CASCADE, permission text NOT NULL CHECK (permission IN ('reviewCases','grade')), granted boolean NOT NULL DEFAULT false, UNIQUE (organization_id, assignment_id, permission));

CREATE TABLE requirement_sets (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), department_id uuid NOT NULL REFERENCES departments(id), academic_year_id uuid NOT NULL REFERENCES academic_years(id), academic_level_id uuid NOT NULL REFERENCES academic_levels(id), title text NOT NULL, status version_status NOT NULL DEFAULT 'DRAFT', revision integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE requirement_set_versions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), requirement_set_id uuid NOT NULL REFERENCES requirement_sets(id), version_number integer NOT NULL, status version_status NOT NULL DEFAULT 'DRAFT', effective_at timestamptz, published_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (organization_id, requirement_set_id, version_number));
CREATE UNIQUE INDEX one_published_requirement_version_scope ON requirement_set_versions(organization_id, requirement_set_id) WHERE status='PUBLISHED';
CREATE TABLE requirements (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), requirement_set_version_id uuid NOT NULL REFERENCES requirement_set_versions(id), code text NOT NULL, label text NOT NULL, required_count integer NOT NULL CHECK(required_count > 0), UNIQUE (organization_id, requirement_set_version_id, code));
CREATE TABLE grading_policy_versions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), department_id uuid NOT NULL REFERENCES departments(id), version_number integer NOT NULL, status version_status NOT NULL DEFAULT 'DRAFT', definition jsonb NOT NULL DEFAULT '{}'::jsonb, published_at timestamptz, UNIQUE (organization_id, department_id, version_number));
CREATE TABLE case_sheet_template_versions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), department_id uuid NOT NULL REFERENCES departments(id), version_number integer NOT NULL, status version_status NOT NULL DEFAULT 'DRAFT', definition jsonb NOT NULL DEFAULT '{}'::jsonb, published_at timestamptz, UNIQUE (organization_id, department_id, version_number));
CREATE TABLE clinical_workflow_policy_versions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), department_id uuid NOT NULL REFERENCES departments(id), version_number integer NOT NULL, status version_status NOT NULL DEFAULT 'DRAFT', definition jsonb NOT NULL DEFAULT '{}'::jsonb, published_at timestamptz, UNIQUE (organization_id, department_id, version_number));

CREATE TABLE student_drafts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), student_id uuid NOT NULL REFERENCES students(id), enrollment_id uuid NOT NULL REFERENCES academic_enrollments(id), term_id uuid NOT NULL REFERENCES terms(id), template_version_id uuid NOT NULL REFERENCES case_sheet_template_versions(id), payload jsonb NOT NULL, revision integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE case_sheets (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), student_id uuid NOT NULL REFERENCES students(id), enrollment_id uuid NOT NULL REFERENCES academic_enrollments(id), department_id uuid NOT NULL REFERENCES departments(id), term_id uuid NOT NULL REFERENCES terms(id), current_status submission_status NOT NULL DEFAULT 'DRAFT', revision integer NOT NULL DEFAULT 1, latest_snapshot_id uuid, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE submission_snapshots (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), case_sheet_id uuid NOT NULL REFERENCES case_sheets(id), student_id uuid NOT NULL REFERENCES students(id), enrollment_id uuid NOT NULL REFERENCES academic_enrollments(id), department_id uuid NOT NULL REFERENCES departments(id), term_id uuid NOT NULL REFERENCES terms(id), academic_year_id uuid NOT NULL REFERENCES academic_years(id), academic_level_id uuid NOT NULL REFERENCES academic_levels(id), cohort_id uuid NOT NULL REFERENCES cohorts(id), group_id uuid REFERENCES academic_groups(id), supervisor_assignment_id uuid REFERENCES supervisor_assignments(id), workflow_policy_version_id uuid NOT NULL REFERENCES clinical_workflow_policy_versions(id), requirement_set_version_id uuid NOT NULL REFERENCES requirement_set_versions(id), requirement_id uuid REFERENCES requirements(id), template_version_id uuid NOT NULL REFERENCES case_sheet_template_versions(id), grading_policy_version_id uuid REFERENCES grading_policy_versions(id), payload jsonb NOT NULL, attachment_snapshot jsonb NOT NULL DEFAULT '[]'::jsonb, sequence integer NOT NULL, resubmission_of_snapshot_id uuid REFERENCES submission_snapshots(id), submitted_at timestamptz NOT NULL DEFAULT now(), UNIQUE (organization_id, case_sheet_id, sequence));
ALTER TABLE case_sheets ADD CONSTRAINT case_sheets_latest_snapshot_fk FOREIGN KEY (latest_snapshot_id) REFERENCES submission_snapshots(id);
CREATE TABLE revision_requests (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), snapshot_id uuid NOT NULL REFERENCES submission_snapshots(id), requested_by_account_id uuid NOT NULL REFERENCES accounts(id), reason text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE clinical_decisions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), snapshot_id uuid NOT NULL REFERENCES submission_snapshots(id), decision_type text NOT NULL CHECK(decision_type IN ('APPROVE_START','APPROVE_FINAL','REQUEST_REVISION')), decided_by_account_id uuid NOT NULL REFERENCES accounts(id), reason text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE supervisor_notes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), snapshot_id uuid NOT NULL REFERENCES submission_snapshots(id), author_account_id uuid NOT NULL REFERENCES accounts(id), body text NOT NULL, student_visible boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE grade_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), snapshot_id uuid NOT NULL REFERENCES submission_snapshots(id), actor_account_id uuid NOT NULL REFERENCES accounts(id), action text NOT NULL CHECK(action IN ('RECORDED','AMENDED')), previous_grade numeric(5,2), new_grade numeric(5,2) NOT NULL CHECK(new_grade >= 0), max_grade numeric(5,2) NOT NULL CHECK(max_grade > 0), reason text, comment text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), CHECK(new_grade <= max_grade), CHECK(action <> 'AMENDED' OR reason IS NOT NULL));
CREATE TABLE assessment_rubric_versions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), department_id uuid NOT NULL REFERENCES departments(id), version_number integer NOT NULL, status version_status NOT NULL DEFAULT 'DRAFT', definition jsonb NOT NULL DEFAULT '{}'::jsonb, UNIQUE (organization_id, department_id, version_number));
CREATE TABLE assessment_snapshots (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), student_id uuid NOT NULL REFERENCES students(id), enrollment_id uuid NOT NULL REFERENCES academic_enrollments(id), rubric_version_id uuid NOT NULL REFERENCES assessment_rubric_versions(id), payload jsonb NOT NULL, score numeric(6,2) NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE student_assessment_summaries (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), student_id uuid NOT NULL REFERENCES students(id), enrollment_id uuid NOT NULL REFERENCES academic_enrollments(id), calculated_at timestamptz NOT NULL DEFAULT now(), formula_version_id uuid, score numeric(6,2), UNIQUE (organization_id, student_id, enrollment_id));
CREATE TABLE final_grade_formula_versions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), department_id uuid NOT NULL REFERENCES departments(id), version_number integer NOT NULL, status version_status NOT NULL DEFAULT 'DRAFT', definition jsonb NOT NULL DEFAULT '{}'::jsonb, UNIQUE (organization_id, department_id, version_number));
CREATE TABLE term_result_closures (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), department_id uuid NOT NULL REFERENCES departments(id), term_id uuid NOT NULL REFERENCES terms(id), academic_level_id uuid NOT NULL REFERENCES academic_levels(id), cohort_id uuid NOT NULL REFERENCES cohorts(id), status term_result_status NOT NULL DEFAULT 'DRAFT', revision integer NOT NULL DEFAULT 1, approved_by_account_id uuid REFERENCES accounts(id), locked_by_account_id uuid REFERENCES accounts(id), reopened_by_account_id uuid REFERENCES accounts(id), reopen_reason text, updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE (organization_id, department_id, term_id, academic_level_id, cohort_id), CHECK(status <> 'REOPENED' OR reopen_reason IS NOT NULL));

CREATE TABLE file_objects (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), object_key text NOT NULL UNIQUE, sha256 text NOT NULL, content_type text NOT NULL, byte_size bigint NOT NULL CHECK(byte_size > 0 AND byte_size <= 26214400), created_by_account_id uuid REFERENCES accounts(id), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE attachments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), file_object_id uuid NOT NULL REFERENCES file_objects(id), snapshot_id uuid REFERENCES submission_snapshots(id), draft_id uuid REFERENCES student_drafts(id), created_at timestamptz NOT NULL DEFAULT now(), CHECK((snapshot_id IS NOT NULL)::int + (draft_id IS NOT NULL)::int = 1));
CREATE TABLE idempotency_keys (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), actor_account_id uuid NOT NULL REFERENCES accounts(id), key text NOT NULL, request_hash text NOT NULL, response_status integer NOT NULL, response_body jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), expires_at timestamptz NOT NULL, UNIQUE (organization_id, actor_account_id, key));
CREATE TABLE audit_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), actor_account_id uuid REFERENCES accounts(id), actor_role role_code, action text NOT NULL, entity_type text NOT NULL, entity_id uuid, department_id uuid REFERENCES departments(id), correlation_id uuid NOT NULL, reason text, before_state jsonb, after_state jsonb, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE outbox_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), topic text NOT NULL, payload jsonb NOT NULL, occurred_at timestamptz NOT NULL DEFAULT now(), processed_at timestamptz, attempts integer NOT NULL DEFAULT 0);

CREATE OR REPLACE FUNCTION reject_immutable_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'immutable record'; END; $$;
CREATE TRIGGER submission_snapshots_immutable BEFORE UPDATE OR DELETE ON submission_snapshots FOR EACH ROW EXECUTE FUNCTION reject_immutable_mutation();
CREATE TRIGGER audit_events_append_only BEFORE UPDATE OR DELETE ON audit_events FOR EACH ROW EXECUTE FUNCTION reject_immutable_mutation();
CREATE TRIGGER grade_events_append_only BEFORE UPDATE OR DELETE ON grade_events FOR EACH ROW EXECUTE FUNCTION reject_immutable_mutation();

CREATE OR REPLACE FUNCTION reject_locked_case_state_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
  IF NEW.current_status IS DISTINCT FROM OLD.current_status AND EXISTS (
    SELECT 1 FROM academic_enrollments e
    JOIN term_result_closures trc ON trc.department_id=OLD.department_id AND trc.term_id=OLD.term_id AND trc.academic_level_id=e.academic_level_id AND trc.cohort_id=e.cohort_id
    WHERE e.id=OLD.enrollment_id AND trc.status='LOCKED'
  ) THEN RAISE EXCEPTION 'academic term result is locked'; END IF;
  RETURN NEW;
END; $$;
CREATE TRIGGER case_sheet_term_lock_guard BEFORE UPDATE ON case_sheets FOR EACH ROW EXECUTE FUNCTION reject_locked_case_state_mutation();

CREATE OR REPLACE FUNCTION reject_locked_snapshot_event() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
  IF EXISTS (
    SELECT 1 FROM submission_snapshots ss
    JOIN term_result_closures trc ON trc.department_id=ss.department_id AND trc.term_id=ss.term_id AND trc.academic_level_id=ss.academic_level_id AND trc.cohort_id=ss.cohort_id
    WHERE ss.id=NEW.snapshot_id AND trc.status='LOCKED'
  ) THEN RAISE EXCEPTION 'academic term result is locked'; END IF;
  RETURN NEW;
END; $$;
CREATE TRIGGER revision_request_term_lock_guard BEFORE INSERT ON revision_requests FOR EACH ROW EXECUTE FUNCTION reject_locked_snapshot_event();
CREATE TRIGGER clinical_decision_term_lock_guard BEFORE INSERT ON clinical_decisions FOR EACH ROW EXECUTE FUNCTION reject_locked_snapshot_event();
CREATE TRIGGER grade_event_term_lock_guard BEFORE INSERT ON grade_events FOR EACH ROW EXECUTE FUNCTION reject_locked_snapshot_event();

CREATE OR REPLACE FUNCTION reject_published_version_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
  IF OLD.status='DRAFT' THEN
    IF TG_OP='DELETE' THEN RETURN OLD; END IF;
    RETURN NEW;
  END IF;
  IF OLD.status='PUBLISHED' AND TG_OP='UPDATE' AND NEW.status='ARCHIVED' AND (to_jsonb(NEW)-'status')=(to_jsonb(OLD)-'status') THEN
    RETURN NEW;
  END IF;
  RAISE EXCEPTION 'published version is immutable';
END; $$;
CREATE TRIGGER requirement_set_versions_published_immutable BEFORE UPDATE OR DELETE ON requirement_set_versions FOR EACH ROW EXECUTE FUNCTION reject_published_version_mutation();
CREATE TRIGGER grading_policy_versions_published_immutable BEFORE UPDATE OR DELETE ON grading_policy_versions FOR EACH ROW EXECUTE FUNCTION reject_published_version_mutation();
CREATE TRIGGER case_sheet_template_versions_published_immutable BEFORE UPDATE OR DELETE ON case_sheet_template_versions FOR EACH ROW EXECUTE FUNCTION reject_published_version_mutation();
CREATE TRIGGER clinical_workflow_policy_versions_published_immutable BEFORE UPDATE OR DELETE ON clinical_workflow_policy_versions FOR EACH ROW EXECUTE FUNCTION reject_published_version_mutation();
CREATE TRIGGER assessment_rubric_versions_published_immutable BEFORE UPDATE OR DELETE ON assessment_rubric_versions FOR EACH ROW EXECUTE FUNCTION reject_published_version_mutation();
CREATE TRIGGER final_grade_formula_versions_published_immutable BEFORE UPDATE OR DELETE ON final_grade_formula_versions FOR EACH ROW EXECUTE FUNCTION reject_published_version_mutation();

CREATE OR REPLACE FUNCTION validate_roster_membership() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE r rosters; e academic_enrollments; BEGIN SELECT * INTO r FROM rosters WHERE id=NEW.roster_id; SELECT * INTO e FROM academic_enrollments WHERE id=NEW.enrollment_id; IF r IS NULL OR e IS NULL OR NEW.organization_id<>r.organization_id OR NEW.organization_id<>e.organization_id OR NEW.student_id<>e.student_id OR NEW.status='ACTIVE' AND (r.status<>'ACTIVE' OR e.status<>'ACTIVE' OR r.academic_year_id<>e.academic_year_id OR r.academic_level_id<>e.academic_level_id OR r.cohort_id<>e.cohort_id) THEN RAISE EXCEPTION 'invalid roster membership'; END IF; RETURN NEW; END; $$;
CREATE TRIGGER roster_membership_compatibility BEFORE INSERT OR UPDATE ON roster_memberships FOR EACH ROW EXECUTE FUNCTION validate_roster_membership();
CREATE OR REPLACE FUNCTION validate_group_membership() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE g academic_groups; p department_distribution_policies; e academic_enrollments; BEGIN SELECT * INTO g FROM academic_groups WHERE id=NEW.group_id; SELECT * INTO p FROM department_distribution_policies WHERE organization_id=NEW.organization_id AND department_id=NEW.department_id AND academic_year_id=g.academic_year_id AND academic_level_id=g.academic_level_id; SELECT * INTO e FROM academic_enrollments WHERE id=NEW.enrollment_id; IF g IS NULL OR p IS NULL OR e IS NULL OR p.mode<>'GROUPS_ENABLED' OR NEW.organization_id<>g.organization_id OR NEW.student_id<>e.student_id OR e.status<>'ACTIVE' OR g.status<>'ACTIVE' OR g.department_id<>NEW.department_id OR e.academic_year_id<>g.academic_year_id OR e.academic_level_id<>g.academic_level_id THEN RAISE EXCEPTION 'invalid group membership'; END IF; RETURN NEW; END; $$;
CREATE TRIGGER group_membership_distribution_guard BEFORE INSERT OR UPDATE ON group_memberships FOR EACH ROW EXECUTE FUNCTION validate_group_membership();

DO $$ DECLARE tbl text; BEGIN FOR tbl IN SELECT unnest(ARRAY['colleges','departments','academic_years','terms','academic_levels','cohorts','accounts','account_scopes','sessions','invitations','students','academic_enrollments','rosters','roster_memberships','department_distribution_policies','academic_groups','group_memberships','faculty_profiles','supervisor_assignments','supervisor_assignment_permissions','requirement_sets','requirement_set_versions','requirements','grading_policy_versions','case_sheet_template_versions','clinical_workflow_policy_versions','student_drafts','case_sheets','submission_snapshots','revision_requests','clinical_decisions','supervisor_notes','grade_events','assessment_rubric_versions','assessment_snapshots','student_assessment_summaries','final_grade_formula_versions','term_result_closures','file_objects','attachments','idempotency_keys','audit_events','outbox_events']) LOOP EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', tbl); EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', tbl); EXECUTE format('CREATE POLICY tenant_isolation ON %I USING (organization_id = current_setting(''app.organization_id'', true)::uuid) WITH CHECK (organization_id = current_setting(''app.organization_id'', true)::uuid)', tbl); END LOOP; END $$;

ALTER TABLE organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE organizations FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON organizations USING (id = current_setting('app.organization_id', true)::uuid) WITH CHECK (id = current_setting('app.organization_id', true)::uuid);

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='dentpilot_app' AND NOT rolsuper AND NOT rolbypassrls) THEN
    RAISE EXCEPTION 'dentpilot_app must exist with NOSUPERUSER and NOBYPASSRLS before migration';
  END IF;
END $$;
GRANT USAGE ON SCHEMA public TO dentpilot_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO dentpilot_app;
REVOKE ALL ON TABLE schema_migrations FROM dentpilot_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO dentpilot_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO dentpilot_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO dentpilot_app;
