import 'dotenv/config';
import crypto from 'node:crypto';
import Fastify, { type FastifyInstance, type FastifyRequest, type FastifySchema } from 'fastify';
import cookie from '@fastify/cookie';
import cors from '@fastify/cors';
import helmet from '@fastify/helmet';
import rateLimit from '@fastify/rate-limit';
import swagger from '@fastify/swagger';
import swaggerUi from '@fastify/swagger-ui';
import { z } from 'zod';
import { DomainError } from '@dentpilot/domain';
import { loadConfig, type AppConfig } from '@dentpilot/config';
import { Database } from './infrastructure/db.js';
import { ObjectStorage } from './infrastructure/object-storage.js';
import { IdempotencyService } from './infrastructure/idempotency.js';
import { AuthService, type Principal } from './security/auth.js';
import { AuthorizationService } from './security/authorization.js';
import { ApiProblem, sendProblem } from './security/errors.js';
import { AuditService } from './modules/audit/service.js';
import { StudentsService } from './modules/students/service.js';
import { GroupsService } from './modules/groups/service.js';
import { CasesService } from './modules/cases/service.js';
import { ResultsService } from './modules/results/service.js';
import { ReportingService } from './modules/reporting/service.js';
import { FilesService } from './modules/files/service.js';

const loginSchema=z.object({organizationId:z.string().uuid(),email:z.string().email().max(254),password:z.string().min(12).max(256)}).strict();
const idempotencySchema=z.string().min(16).max(200).regex(/^[A-Za-z0-9._-]+$/);
const uuid={type:'string',format:'uuid'} as const;
const idempotency={type:'string',minLength:16,maxLength:200,pattern:'^[A-Za-z0-9._-]+$'} as const;
const problem={type:'object',required:['error'],additionalProperties:false,properties:{error:{type:'object',required:['code','message','requestId'],additionalProperties:false,properties:{code:{type:'string'},message:{type:'string'},requestId:{type:'string'},details:{type:'object',additionalProperties:{type:'array',items:{type:'string'}}}}}}} as const;
const problems={400:problem,401:problem,403:problem,404:problem,409:problem,429:problem,500:problem};
const objectResponse={type:'object',additionalProperties:true} as const;
export const routeSchemas = {
  live:{summary:'Liveness probe',response:{200:{type:'object',required:['status'],properties:{status:{const:'live'}}}}},
  ready:{summary:'Dependency readiness probe',response:{200:objectResponse,503:objectResponse}},
  openapi:{summary:'OpenAPI document',response:{200:objectResponse}},
  login:{summary:'Create a tenant session',body:{type:'object',required:['organizationId','email','password'],additionalProperties:false,properties:{organizationId:uuid,email:{type:'string',format:'email',maxLength:254},password:{type:'string',minLength:12,maxLength:256}}},response:{204:{type:'null'},...problems}},
  logout:{summary:'Revoke the current session',response:{204:{type:'null'},...problems}},
  session:{summary:'Read the current session actor',response:{200:{type:'object',required:['accountId','organizationId','role','departmentIds'],additionalProperties:false,properties:{accountId:uuid,organizationId:uuid,role:{type:'string',enum:['UNIVERSITY_ADMIN','DEPARTMENT_ADMIN','CLINICAL_SUPERVISOR','STUDENT_INTEGRATION']},departmentIds:{type:'array',items:uuid}}},...problems}},
  invitation:{summary:'Issue an invitation',body:{type:'object',required:['email','role'],additionalProperties:false,properties:{email:{type:'string',format:'email'},role:{type:'string',enum:['UNIVERSITY_ADMIN','DEPARTMENT_ADMIN','CLINICAL_SUPERVISOR','STUDENT_INTEGRATION']}}},response:{201:objectResponse,...problems}},
  redeem:{summary:'Redeem an invitation once',body:{type:'object',required:['organizationId','token','password'],additionalProperties:false,properties:{organizationId:uuid,token:{type:'string',minLength:40},password:{type:'string',minLength:12,maxLength:256}}},response:{204:{type:'null'},...problems}},
  students:{summary:'List students in the actor scope',querystring:{type:'object',additionalProperties:false,properties:{departmentId:uuid}},response:{200:{type:'array',items:objectResponse},...problems}},
  closeEnrollment:{summary:'Close an enrollment atomically',params:{type:'object',required:['id'],properties:{id:uuid}},body:{type:'object',required:['expectedRevision','reason','idempotencyKey'],additionalProperties:false,properties:{expectedRevision:{type:'integer',minimum:1},reason:{type:'string',minLength:3,maxLength:500},idempotencyKey:idempotency}},response:{204:{type:'null'},...problems}},
  groupMembership:{summary:'Assign or move a group membership',body:{type:'object',required:['groupId','enrollmentId','departmentId','studentId','idempotencyKey'],additionalProperties:false,properties:{groupId:uuid,enrollmentId:uuid,departmentId:uuid,studentId:uuid,idempotencyKey:idempotency}},response:{204:{type:'null'},...problems}},
  submit:{summary:'Submit a student draft as an immutable snapshot',body:{type:'object',required:['draftId','idempotencyKey'],additionalProperties:false,properties:{draftId:uuid,idempotencyKey:idempotency}},response:{201:{type:'object',required:['snapshotId'],additionalProperties:false,properties:{snapshotId:uuid}},...problems}},
  staffSubmission:{summary:'Read a submitted case in staff scope',params:{type:'object',required:['id'],properties:{id:uuid}},response:{200:objectResponse,...problems}},
  revision:{summary:'Request revision of a submitted case',params:{type:'object',required:['id'],properties:{id:uuid}},body:{type:'object',required:['reason','idempotencyKey'],additionalProperties:false,properties:{reason:{type:'string',minLength:3,maxLength:1000},idempotencyKey:idempotency}},response:{204:{type:'null'},...problems}},
  approval:{summary:'Apply an authorized clinical approval transition',params:{type:'object',required:['id'],properties:{id:uuid}},body:{type:'object',required:['idempotencyKey'],additionalProperties:false,properties:{idempotencyKey:idempotency}},response:{204:{type:'null'},...problems}},
  grade:{summary:'Record or amend a grade',params:{type:'object',required:['id'],properties:{id:uuid}},body:{type:'object',required:['grade','comment','idempotencyKey'],additionalProperties:false,properties:{grade:{type:'number',minimum:0,maximum:100},comment:{type:'string',minLength:1,maxLength:2000},reason:{type:'string',maxLength:1000},idempotencyKey:idempotency}},response:{204:{type:'null'},...problems}},
  termResult:{summary:'Transition a term result with optimistic concurrency',params:{type:'object',required:['id'],properties:{id:uuid}},body:{type:'object',required:['expectedRevision','idempotencyKey'],additionalProperties:false,properties:{expectedRevision:{type:'integer',minimum:1},reason:{type:'string',maxLength:1000},idempotencyKey:idempotency}},response:{204:{type:'null'},...problems}},
  aggregate:{summary:'Read aggregate-only academic reporting',querystring:{type:'object',required:['academicYearId'],additionalProperties:false,properties:{academicYearId:uuid}},response:{200:{type:'object',required:['organizationId','academicYearId','totalStudents','totalSubmittedCases','pendingClinicalDecisions','generatedAt'],additionalProperties:false,properties:{organizationId:uuid,academicYearId:uuid,totalStudents:{type:'integer'},totalSubmittedCases:{type:'integer'},pendingClinicalDecisions:{type:'integer'},generatedAt:{type:'string',format:'date-time'}}},...problems}},
  upload:{summary:'Create a private file record and signed upload',body:{type:'object',required:['contentType','byteSize','sha256','idempotencyKey'],additionalProperties:false,properties:{contentType:{type:'string',enum:['application/pdf','image/jpeg','image/png','image/webp']},byteSize:{type:'integer',minimum:1,maximum:26214400},sha256:{type:'string',pattern:'^[a-fA-F0-9]{64}$'},idempotencyKey:idempotency}},response:{201:objectResponse,...problems}},
  read:{summary:'Create an authorized signed read URL',params:{type:'object',required:['id'],properties:{id:uuid}},response:{200:objectResponse,...problems}},
} satisfies Record<string, FastifySchema>;

export interface ProductionCore { app: FastifyInstance; db: Database; config: AppConfig; }
export async function buildApp(env: NodeJS.ProcessEnv=process.env, options: {initializeObjectStorage?:boolean}={}): Promise<ProductionCore> {
  const config=loadConfig(env); const db=new Database(config.DATABASE_URL); const storage=new ObjectStorage(config.MINIO_ENDPOINT,config.MINIO_ACCESS_KEY,config.MINIO_SECRET_KEY); if(options.initializeObjectStorage!==false) await storage.ensureBucket(); const app=Fastify({logger:{level:env.NODE_ENV==='production'?'info':'warn'},bodyLimit:1024*1024,genReqId:()=>crypto.randomUUID(),ajv:{customOptions:{removeAdditional:false}}});
  const auth=new AuthService(db,config.NODE_ENV==='production'); const authorization=new AuthorizationService(); const audit=new AuditService(); const idempotency=new IdempotencyService(); const students=new StudentsService(authorization,audit,idempotency); const groups=new GroupsService(authorization,audit,idempotency); const cases=new CasesService(authorization,audit,idempotency); const results=new ResultsService(authorization,audit,idempotency); const reporting=new ReportingService(authorization); const files=new FilesService(authorization,idempotency,storage);
  await app.register(cookie,{secret:config.SESSION_COOKIE_SECRET}); await app.register(helmet,{contentSecurityPolicy:{directives:{defaultSrc:["'none'"],frameAncestors:["'none'"]}}}); await app.register(cors,{origin:config.CORS_ORIGIN,credentials:true}); await app.register(rateLimit,{global:false}); await app.register(swagger,{openapi:{info:{title:'DentPilot University Production API',version:'v1.0-phase1'},servers:[{url:'/'}]}}); await app.register(swaggerUi,{routePrefix:'/docs'});
  app.addHook('onResponse',async(request,reply)=>{ request.log.info({requestId:request.id,route:request.routeOptions.url,status:reply.statusCode},'request_completed'); });
  app.setErrorHandler((error,request,reply)=>{ if(error instanceof ApiProblem) return sendProblem(reply,request.id,error); if(error instanceof DomainError) { const status=error.code==='CONFLICT'||error.code==='ILLEGAL_TRANSITION'||error.code==='IMMUTABLE_RECORD'?409:400; return sendProblem(reply,request.id,new ApiProblem(status,error.code,error.message)); } if(typeof error === 'object' && error !== null && 'statusCode' in error && error.statusCode === 429) return sendProblem(reply,request.id,new ApiProblem(429,'RATE_LIMITED','Too many requests. Retry later.')); if(error instanceof z.ZodError) { const flattened=error.flatten(); const details=Object.fromEntries(Object.entries(flattened.fieldErrors).filter((entry): entry is [string,string[]] => Array.isArray(entry[1]))); if(flattened.formErrors.length) details._form=flattened.formErrors; return sendProblem(reply,request.id,new ApiProblem(400,'VALIDATION_ERROR','Request validation failed.',details)); } if(typeof error === 'object' && error !== null && 'statusCode' in error && error.statusCode === 400) return sendProblem(reply,request.id,new ApiProblem(400,'VALIDATION_ERROR','Request validation failed.')); const message=error instanceof Error ? error.message : 'unknown_error'; request.log.error({requestId:request.id,errorCode:'INTERNAL_ERROR',message},'request_failed'); return sendProblem(reply,request.id,new ApiProblem(500,'INTERNAL_ERROR','An internal error occurred.')); });
  const principal=async(request:FastifyRequest):Promise<Principal>=>auth.authenticate(request);
  const mutation=async(request:FastifyRequest):Promise<Principal>=>{ const p=await principal(request); await auth.assertCsrf(request,p); return p; };
  app.get('/health/live',{schema:routeSchemas.live},async()=>({status:'live'})); app.get('/health/ready',{schema:routeSchemas.ready},async(_request,reply)=>{ const ready=(await db.readiness()) && (await storage.readiness()); return reply.code(ready?200:503).send({status:ready?'ready':'not_ready'}); });
  app.get('/openapi.json',{schema:routeSchemas.openapi},async()=>app.swagger());
  app.post('/api/v1/auth/login',{schema:routeSchemas.login,config:{rateLimit:{max:5,timeWindow:'1 minute'}}},async(request,reply)=>{ const body=loginSchema.parse(request.body); const session=await auth.login(body.organizationId,body.email,body.password,request.id); auth.setCookies(reply,session.sessionValue,session.csrfToken); return reply.code(204).send(); });
  app.post('/api/v1/auth/logout',{schema:routeSchemas.logout},async(request,reply)=>{ const p=await mutation(request); await auth.logout(request,p,request.id); auth.clearCookies(reply); return reply.code(204).send(); });
  app.get('/api/v1/session',{schema:routeSchemas.session},async(request)=>{ const p=await principal(request); return {accountId:p.accountId,organizationId:p.organizationId,role:p.role,departmentIds:p.departmentIds}; });
  app.post('/api/v1/invitations',{schema:routeSchemas.invitation},async(request,reply)=>{ const p=await mutation(request); const body=z.object({email:z.string().email(),role:z.enum(['UNIVERSITY_ADMIN','DEPARTMENT_ADMIN','CLINICAL_SUPERVISOR','STUDENT_INTEGRATION'])}).strict().parse(request.body); await db.withTenant(p,async(client)=>authorization.assert(client,p,'invitations:issue')); const token=await auth.issueInvitation(p,body.email,body.role,request.id); return reply.code(201).send({invitationToken:config.NODE_ENV==='development'?token:undefined}); });
  app.post('/api/v1/invitations/redeem',{schema:routeSchemas.redeem},async(request,reply)=>{ const body=z.object({organizationId:z.string().uuid(),token:z.string().min(40),password:z.string().min(12).max(256)}).strict().parse(request.body); await auth.redeemInvitation(body.organizationId,body.token,body.password,request.id); return reply.code(204).send(); });
  app.get('/api/v1/students',{schema:routeSchemas.students},async(request)=>{ const p=await principal(request); const departmentId=z.object({departmentId:z.string().uuid().optional()}).parse(request.query).departmentId; return db.withTenant(p,(client)=>students.list(client,p,departmentId)); });
  app.post('/api/v1/enrollments/:id/close',{schema:routeSchemas.closeEnrollment},async(request,reply)=>{ const p=await mutation(request); const body=z.object({expectedRevision:z.number().int().positive(),reason:z.string().min(3).max(500),idempotencyKey:idempotencySchema}).strict().parse(request.body); const id=z.object({id:z.string().uuid()}).parse(request.params).id; await db.withTenant(p,(client)=>students.closeEnrollment(client,p,id,body.expectedRevision,body.reason,body.idempotencyKey,request.id)); return reply.code(204).send(); });
  app.post('/api/v1/groups/memberships',{schema:routeSchemas.groupMembership},async(request,reply)=>{ const p=await mutation(request); const body=z.object({groupId:z.string().uuid(),enrollmentId:z.string().uuid(),departmentId:z.string().uuid(),studentId:z.string().uuid(),idempotencyKey:idempotencySchema}).strict().parse(request.body); await db.withTenant(p,(client)=>groups.assignMembership(client,p,{...body,correlationId:request.id})); return reply.code(204).send(); });
  app.post('/api/v1/student/submissions',{schema:routeSchemas.submit},async(request,reply)=>{ const p=await mutation(request); const body=z.object({draftId:z.string().uuid(),idempotencyKey:idempotencySchema}).strict().parse(request.body); const result=await db.withTenant(p,(client)=>cases.submitDraft(client,p,{...body,correlationId:request.id})); return reply.code(201).send(result); });
  app.get('/api/v1/staff/submissions/:id',{schema:routeSchemas.staffSubmission},async(request)=>{ const p=await principal(request); const id=z.object({id:z.string().uuid()}).parse(request.params).id; return db.withTenant(p,async(client)=>{ const row=await client.query<{id:string;department_id:string;supervisor_assignment_id:string;status:string;submitted_at:Date;academic_year_id:string;academic_level_id:string;cohort_id:string;group_id:string|null}>('SELECT ss.id,ss.department_id,ss.supervisor_assignment_id,cs.current_status AS status,ss.submitted_at,ss.academic_year_id,ss.academic_level_id,ss.cohort_id,ss.group_id FROM submission_snapshots ss JOIN case_sheets cs ON cs.id=ss.case_sheet_id AND cs.latest_snapshot_id=ss.id WHERE ss.id=$1',[id]); if(!row.rowCount) throw new ApiProblem(404,'NOT_FOUND','Submitted case not found.'); const submission=row.rows[0]; await authorization.assert(client,p,'cases:review',{departmentId:submission.department_id,academicYearId:submission.academic_year_id,academicLevelId:submission.academic_level_id,cohortId:submission.cohort_id,groupId:submission.group_id ?? undefined,assignmentId:submission.supervisor_assignment_id,assignmentPermission:'reviewCases'}); return submission; }); });
  app.post('/api/v1/staff/submissions/:id/revision-requests',{schema:routeSchemas.revision},async(request,reply)=>{ const p=await mutation(request); const id=z.object({id:z.string().uuid()}).parse(request.params).id; const body=z.object({reason:z.string().min(3).max(1000),idempotencyKey:idempotencySchema}).strict().parse(request.body); await db.withTenant(p,(client)=>cases.requestRevision(client,p,id,body.reason,body.idempotencyKey,request.id)); return reply.code(204).send(); });
  for(const [path,target] of [['approve-start','APPROVED_START'],['approve-final','APPROVED_FINAL']] as const) app.post(`/api/v1/staff/submissions/:id/${path}`,{schema:{...routeSchemas.approval,summary:`Transition a submission to ${target}`}},async(request,reply)=>{ const p=await mutation(request); const id=z.object({id:z.string().uuid()}).parse(request.params).id; const body=z.object({idempotencyKey:idempotencySchema}).strict().parse(request.body); await db.withTenant(p,(client)=>cases.approve(client,p,id,target,body.idempotencyKey,request.id)); return reply.code(204).send(); });
  app.post('/api/v1/staff/submissions/:id/grades',{schema:routeSchemas.grade},async(request,reply)=>{ const p=await mutation(request); const id=z.object({id:z.string().uuid()}).parse(request.params).id; const body=z.object({grade:z.number().min(0).max(100),comment:z.string().min(1).max(2000),reason:z.string().max(1000).optional(),idempotencyKey:idempotencySchema}).strict().parse(request.body); await db.withTenant(p,(client)=>cases.grade(client,p,{...body,snapshotId:id,correlationId:request.id})); return reply.code(204).send(); });
  for(const target of ['reviewed','approved','locked','reopened'] as const) app.post(`/api/v1/term-results/:id/${target}`,{schema:{...routeSchemas.termResult,summary:`Transition a term result to ${target}`}},async(request,reply)=>{ const p=await mutation(request); const id=z.object({id:z.string().uuid()}).parse(request.params).id; const body=z.object({expectedRevision:z.number().int().positive(),reason:z.string().max(1000).optional(),idempotencyKey:idempotencySchema}).strict().parse(request.body); await db.withTenant(p,(client)=>results.transition(client,p,id,target.toUpperCase() as 'REVIEWED'|'APPROVED'|'LOCKED'|'REOPENED',body.expectedRevision,body.reason,body.idempotencyKey,request.id)); return reply.code(204).send(); });
  app.get('/api/v1/reports/aggregate',{schema:routeSchemas.aggregate},async(request)=>{ const p=await principal(request); const query=z.object({academicYearId:z.string().uuid()}).parse(request.query); return db.withTenant(p,(client)=>reporting.aggregate(client,p,query.academicYearId)); });
  app.post('/api/v1/files/presign-upload',{schema:routeSchemas.upload},async(request,reply)=>{ const p=await mutation(request); const body=z.object({contentType:z.enum(['application/pdf','image/jpeg','image/png','image/webp']),byteSize:z.number().int().positive().max(26214400),sha256:z.string().regex(/^[a-f0-9]{64}$/i),idempotencyKey:idempotencySchema}).strict().parse(request.body); const result=await db.withTenant(p,(client)=>files.presignUpload(client,p,body)); return reply.code(201).send(result); });
  app.get('/api/v1/files/:id/presign-read',{schema:routeSchemas.read},async(request)=>{ const p=await principal(request); const id=z.object({id:z.string().uuid()}).parse(request.params).id; return db.withTenant(p,(client)=>files.presignRead(client,p,id)); });
  app.addHook('onClose',async()=>db.close()); return {app,db,config};
}
