import type { PoolClient } from 'pg';
import { assertGradeAmendment, assertSubmissionTransition } from '@dentpilot/domain';
import type { Principal } from '../../security/auth.js';
import { ApiProblem } from '../../security/errors.js';
import { AuthorizationService } from '../../security/authorization.js';
import { AuditService } from '../audit/service.js';

export class CasesService {
  constructor(private readonly authorization: AuthorizationService, private readonly audit: AuditService) {}
  async submitDraft(client: PoolClient, principal: Principal, input: { draftId:string; idempotencyKey:string; correlationId:string }): Promise<{snapshotId:string}> {
    if (!principal.studentId) throw new ApiProblem(403,'FORBIDDEN','Only a student integration principal can submit a draft.');
    const existingKey=await client.query<{response_body:{snapshotId:string}}>('SELECT response_body FROM idempotency_keys WHERE actor_account_id=$1 AND key=$2',[principal.accountId,input.idempotencyKey]); if(existingKey.rowCount) return existingKey.rows[0].response_body;
    const draft=await client.query<{id:string;student_id:string;enrollment_id:string;template_version_id:string;payload:Record<string,unknown>}>('SELECT id,student_id,enrollment_id,template_version_id,payload FROM student_drafts WHERE id=$1 FOR UPDATE',[input.draftId]);
    if (!draft.rowCount || draft.rows[0].student_id!==principal.studentId) throw new ApiProblem(404,'NOT_FOUND','Draft not found.'); const d=draft.rows[0];
    const enrollment=await client.query<{academic_year_id:string;academic_level_id:string;cohort_id:string}>('SELECT academic_year_id,academic_level_id,cohort_id FROM academic_enrollments WHERE id=$1 AND status=\'ACTIVE\'',[d.enrollment_id]); if(!enrollment.rowCount) throw new ApiProblem(409,'ILLEGAL_TRANSITION','Draft enrollment is not active.');
    const template=await client.query<{department_id:string}>('SELECT department_id FROM case_sheet_template_versions WHERE id=$1 AND status=\'PUBLISHED\'',[d.template_version_id]); if(!template.rowCount) throw new ApiProblem(409,'ILLEGAL_TRANSITION','Template is not published.'); const departmentId=template.rows[0].department_id;
    const policy=await client.query<{id:string}>('SELECT id FROM clinical_workflow_policy_versions WHERE department_id=$1 AND status=\'PUBLISHED\' ORDER BY version_number DESC LIMIT 1',[departmentId]); const req=await client.query<{id:string}>('SELECT rsv.id FROM requirement_sets rs JOIN requirement_set_versions rsv ON rsv.requirement_set_id=rs.id WHERE rs.department_id=$1 AND rsv.status=\'PUBLISHED\' ORDER BY rsv.version_number DESC LIMIT 1',[departmentId]); const grading=await client.query<{id:string}>('SELECT id FROM grading_policy_versions WHERE department_id=$1 AND status=\'PUBLISHED\' ORDER BY version_number DESC LIMIT 1',[departmentId]); const assignment=await client.query<{id:string}>('SELECT id FROM supervisor_assignments WHERE department_id=$1 AND academic_year_id=$2 AND academic_level_id=$3 AND status=\'ACTIVE\' ORDER BY effective_from DESC LIMIT 1',[departmentId,enrollment.rows[0].academic_year_id,enrollment.rows[0].academic_level_id]);
    if(!policy.rowCount||!req.rowCount||!grading.rowCount||!assignment.rowCount) throw new ApiProblem(409,'ILLEGAL_TRANSITION','No effective policy or supervisor assignment exists.');
    const caseSheet=await client.query<{id:string}>('INSERT INTO case_sheets(organization_id,student_id,enrollment_id,department_id,current_status) VALUES($1,$2,$3,$4,$5) RETURNING id',[principal.organizationId,d.student_id,d.enrollment_id,departmentId,'SUBMITTED']); const snapshot=await client.query<{id:string}>('INSERT INTO submission_snapshots(organization_id,case_sheet_id,student_id,enrollment_id,department_id,academic_year_id,academic_level_id,cohort_id,supervisor_assignment_id,workflow_policy_version_id,requirement_set_version_id,template_version_id,grading_policy_version_id,payload,sequence,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,1,$15) RETURNING id',[principal.organizationId,caseSheet.rows[0].id,d.student_id,d.enrollment_id,departmentId,enrollment.rows[0].academic_year_id,enrollment.rows[0].academic_level_id,enrollment.rows[0].cohort_id,assignment.rows[0].id,policy.rows[0].id,req.rows[0].id,d.template_version_id,grading.rows[0].id,d.payload,'SUBMITTED']);
    await client.query('UPDATE case_sheets SET latest_snapshot_id=$1 WHERE id=$2',[snapshot.rows[0].id,caseSheet.rows[0].id]); await client.query('DELETE FROM student_drafts WHERE id=$1',[d.id]); await client.query('INSERT INTO idempotency_keys(organization_id,actor_account_id,key,request_hash,response_status,response_body,expires_at) VALUES($1,$2,$3,$4,201,$5,now()+interval \'24 hours\')',[principal.organizationId,principal.accountId,input.idempotencyKey,'submit-draft',JSON.stringify({snapshotId:snapshot.rows[0].id})]); await this.audit.append(client,principal,{action:'CASE_SUBMITTED',entityType:'submission_snapshot',entityId:snapshot.rows[0].id,departmentId,correlationId:input.correlationId}); return {snapshotId:snapshot.rows[0].id};
  }
  async grade(client: PoolClient, principal: Principal, input: { snapshotId:string; grade:number; comment:string; reason?:string; correlationId:string }): Promise<void> {
    const snapshot=await client.query<{id:string;department_id:string;supervisor_assignment_id:string;status:'SUBMITTED'|'REVISION_REQUESTED'|'APPROVED_START'|'APPROVED_FINAL'|'GRADED'}>('SELECT id,department_id,supervisor_assignment_id,status FROM submission_snapshots WHERE id=$1',[input.snapshotId]); if(!snapshot.rowCount) throw new ApiProblem(404,'NOT_FOUND','Submission not found.'); const s=snapshot.rows[0]; await this.authorization.assert(client,principal,'cases:grade',{departmentId:s.department_id,assignmentId:s.supervisor_assignment_id,assignmentPermission:'grade'}); if(s.status!=='APPROVED_FINAL'&&s.status!=='GRADED') throw new ApiProblem(409,'ILLEGAL_TRANSITION','Submission is not gradeable.'); const prior=await client.query<{new_grade:string}>('SELECT new_grade FROM grade_events WHERE snapshot_id=$1 ORDER BY created_at DESC LIMIT 1',[s.id]); if(prior.rowCount) assertGradeAmendment(input.reason); await client.query('INSERT INTO grade_events(organization_id,snapshot_id,actor_account_id,action,previous_grade,new_grade,max_grade,reason,comment) VALUES($1,$2,$3,$4,$5,$6,100,$7,$8)',[principal.organizationId,s.id,principal.accountId,prior.rowCount?'AMENDED':'RECORDED',prior.rows[0]?.new_grade??null,input.grade,input.reason??null,input.comment]); await this.audit.append(client,principal,{action:prior.rowCount?'GRADE_AMENDED':'GRADE_RECORDED',entityType:'submission_snapshot',entityId:s.id,departmentId:s.department_id,correlationId:input.correlationId,reason:input.reason});
  }
  async requestRevision(client: PoolClient, principal: Principal, snapshotId:string, reason:string, correlationId:string): Promise<void> { const result=await client.query<{department_id:string;supervisor_assignment_id:string;status:'SUBMITTED'|'REVISION_REQUESTED'|'APPROVED_START'|'APPROVED_FINAL'|'GRADED'}>('SELECT department_id,supervisor_assignment_id,status FROM submission_snapshots WHERE id=$1',[snapshotId]); if(!result.rowCount) throw new ApiProblem(404,'NOT_FOUND','Submission not found.'); const s=result.rows[0]; await this.authorization.assert(client,principal,'cases:review',{departmentId:s.department_id,assignmentId:s.supervisor_assignment_id,assignmentPermission:'reviewCases'}); assertSubmissionTransition(s.status,'REVISION_REQUESTED'); await client.query('INSERT INTO revision_requests(organization_id,snapshot_id,requested_by_account_id,reason) VALUES($1,$2,$3,$4)',[principal.organizationId,snapshotId,principal.accountId,reason]); await client.query("UPDATE case_sheets SET current_status='REVISION_REQUESTED' WHERE latest_snapshot_id=$1",[snapshotId]); await this.audit.append(client,principal,{action:'REVISION_REQUESTED',entityType:'submission_snapshot',entityId:snapshotId,departmentId:s.department_id,correlationId,reason}); }
}
